name: Google Cloud Function Deployment

on:
  push:
    branches:
      - main

jobs:
  Deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # Debugging step to check if secrets are available
      - name: Check secrets
        run: |
          echo "Length of GOOGLE_CREDENTIALS: ${#GOOGLE_CREDENTIALS}"
        env:
          GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}

      # Authenticate to Google Cloud using GitHub Secret
      - name: GCP Authentication
        id: "auth"
        uses: google-github-actions/auth@v2
        with:
          credentials_json: "${{ secrets.GOOGLE_CREDENTIALS }}"

      # Debugging step to verify GCP credentials
      - name: Debug GCP credentials
        env:
          GOOGLE_APPLICATION_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
        run: |
          echo "$GOOGLE_APPLICATION_CREDENTIALS" > credentials.json
          echo "Credentials exist: $(ls credentials.json)"

      # Set up Google Cloud SDK
      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2

      # Check gcloud CLI is working
      - name: Use gcloud CLI
        run: "gcloud info"

      # Deploy Cloud Function (Gen 2)
      - name: Deploy a gen 2 cloud function
        run: |
          gcloud functions deploy sistemakreditasi \
            --region=asia-southeast2 \
            --allow-unauthenticated \
            --entry-point=UploadPDF \ # Sesuaikan dengan nama fungsi yang kamu gunakan
            --gen2 \
            --runtime=go122 \
            --trigger-http \
            --timeout=540s \
            --set-env-vars=MONGOSTRING='${{ secrets.MONGOSTRING }}' \
            --set-env-vars=JWT_SECRET='${{ secrets.JWT_SECRET }}' \
            --set-env-vars=PRIVATEKEY='${{ secrets.PRIVATEKEY }}' \
            --set-env-vars=PUBLICKEY='${{ secrets.PUBLICKEY }}' \
            --set-env-vars=GOOGLE_CREDENTIALS='${{ secrets.GOOGLE_CREDENTIALS }}' # Penambahan variabel kredensial

      # Verifikasi apakah fungsi sudah berhasil di-deploy
      - name: Cek eksistensi fungsi
        run: "gcloud functions describe sistemakreditasi --region=asia-southeast2"

      # Cek log untuk debugging
      - name: Cek log debugging
        run: "gcloud functions logs read sistemakreditasi --region=asia-southeast2"

      # Bersihkan Artifact Registry (optional)
      - name: Cleaning Artifact Registry
        run: "gcloud artifacts repositories delete gcf-artifacts --location=asia-southeast2 --quiet"
