name: Google Cloud Function Deployment

on:
  push:
    branches:
      - main

jobs:
  Deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Check secrets
        run: |
          echo "Length of GOOGLE_CREDENTIALS: ${#GOOGLE_CREDENTIALS}"
        env:
          GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}

      - name: GCP Authentication
        id: "auth"
        uses: google-github-actions/auth@v2
        with:
          credentials_json: "${{ secrets.GOOGLE_CREDENTIALS }}"

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2

      - name: Use gcloud CLI
        run: "gcloud info"

      - name: Deploy a gen 2 cloud function
        run: |
          gcloud functions deploy sistemakreditasi \
            --region=asia-southeast2 \
            --allow-unauthenticated \
            --entry-point=WebHook \
            --gen2 \
            --runtime=go122 \
            --trigger-http \
            --timeout=540s \
            --set-env-vars="MONGOSTRING=${{ secrets.MONGOSTRING }},JWT_SECRET=${{ secrets.JWT_SECRET }},PRIVATEKEY=${{ secrets.PRIVATEKEY }},PUBLICKEY=${{ secrets.PUBLICKEY }},GOOGLE_CREDENTIALS=${{ secrets.GOOGLE_CREDENTIALS }}"
      

      - name: Cek eksistensi fungsi
        run: |
          gcloud functions describe sistemakreditasi --region=asia-southeast2

      - name: Cek log debugging
        run: |
          gcloud functions logs read sistemakreditasi --region=asia-southeast2 --limit=50

      - name: Cleaning Artifact Registry
        run: |
          gcloud artifacts repositories delete gcf-artifacts --location=asia-southeast2 --quiet
